### ISSUE TITLE
io.realm.RealmQuery.createQuery(io.realm.Realm, java.lang.Class)' is inaccessible to class 'com.vicpin.krealmextensions.RealmExtensionsKt' .

### ISSUE THREAD

**Issue by pymblesoftware** [vicpinm/Kotlin-Realm-Extensions#50]
I have the following crash which slashdot and google do not have any information on...

 Process: com.agersens.eshepardcollarfitter.production, PID: 9241
                                                                                            java.lang.IllegalAccessError: Method 'io.realm.RealmQuery io.realm.RealmQuery.createQuery(io.realm.Realm, java.lang.Class)' is inaccessible to class 'com.vicpin.krealmextensions.RealmExtensionsKt' (declaration of 'com.vicpin.krealmextensions.RealmExtensionsKt' appears in /data/app/com.agersens.eshepardcollarfitter.production-1/split_lib_dependencies_apk.apk)
                                                                                                at com.vicpin.krealmextensions.RealmExtensionsKt.forEntity(RealmExtensions.kt:246)
                                                                                                at com.vicpin.krealmextensions.RealmExtensionsKt.queryFirst(RealmExtensions.kt:41)
                                                                                                at com.maiatehcology.maialibrary.syncframework.database.DatabaseWrapper.fetchAnimals(DatabaseWrapper.kt:78)

Any hints as to why this might be happening... I used Kotlin realm extensions in another app and it worked and I can't figure out what I did different other than creating two modules, one for the app and one for all the network and realm code...

**Comment by pymblesoftware** [comment]
This was my bad...

You will get this run time error with the wrong versions in the build gradle... pay close attention to the following in the documentation..

compile 'io.reactivex.rxjava2:rxjava:2.1.4'
compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
